# Generated by Django 3.1 on 2021-11-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0002_auto_20211114_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='D:\\Dev\\foodgram-project-react\\backend\\foodgram\\media'),
        ),
    ]
